version: "3.9"
services:
  weather_ui:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather.rule=Host(`weather.crisego.com`)"
      - "traefik.http.routers.weather.entrypoints=websecure"
      - "traefik.http.routers.weather.tls=true"
    networks:
      - traefik-docker-compose_default
networks:
  traefik-docker-compose_default:
    external: true
