name: Deploy to server
on: 
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: [self-hosted, prod]
    steps:
      - name: ========= Server information =========
        run: cat /etc/os-release

  build:
    name: Build and deploy
    runs-on: [self-hosted, linux, x64, prod]
    steps:
    - uses: actions/checkout@master
    - name: ========== Destroy old stack ==========
      run: docker compose down

    - name: ========== Run build ==========
      run: docker compose build --no-cache
    
    - name: =========== Start stack ==========
      run: docker compose up -d
   