name: Deploy to server
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Destroy old stack
      run: docker compose down

    - name: Run build
      run: docker compose build --no-cache
    
    - name: Start stack
      run: docker compose up -d
   