name: Deploy to server
on: 
  pull_request:
    branches:
      - master

jobs:

  build:
    name: ============ Build ============
    runs-on: [self-hosted, linux, x64, prod]
    steps:
    - uses: actions/checkout@master
    - name: Destroy old stack
      run: docker compose down

    - name: ========== Run build ==========
      run: docker compose build --no-cache
    
    - name: =========== Start stack ==========
      run: docker compose up -d
   